### ISSUE TITLE
Ability to specify time limit (-W)

### ISSUE THREAD

**Issue by funnell** [Snakemake-Profiles/snakemake-lsf#13]
Hello, it would be nice to be able to set the job time limit (-W).
It seems like this would require adding an entry to a rule's resources, but it's not clear to me that there is a standard key for this in snakemake.

**Comment by mbhall88** [comment]
Hi @funnell I am in the process of adding the ability to specifc "non-standard" LSF parameters for rules. Follow #7 for updates. I should hopefully have it implemented today or tomorrow. The idea will be that you can specify additional cluster parameters in a special cluster-specific config file `lsf.yaml`. Say you have a rule `foo` and you want to indicate this job should only run for an hour and 5 minutes and should only run on a specific project (say `bigmem`) you could do

`lsf.yaml`
```yaml
foo:
  - "-W 1:05"
  - "-P bigmem"
```
